insert into public.currencies (code, name, symbol)
values
  ('AED', 'UAE Dirham', 'AED'),
  ('AMD', 'Armenian Dram', 'AMD'),
  ('AUD', 'Australian Dollar', 'AUD'),
  ('AZN', 'Azerbaijani Manat', 'AZN'),
  ('BGN', 'Bulgarian Lev', 'BGN'),
  ('BRL', 'Brazilian Real', 'BRL'),
  ('BYN', 'Belarusian Ruble', 'BYN'),
  ('CAD', 'Canadian Dollar', 'CAD'),
  ('CHF', 'Swiss Franc', 'CHF'),
  ('CNY', 'Chinese Yuan', 'CNY'),
  ('CZK', 'Czech Koruna', 'CZK'),
  ('DKK', 'Danish Krone', 'DKK'),
  ('GBP', 'British Pound', 'GBP'),
  ('HKD', 'Hong Kong Dollar', 'HKD'),
  ('HUF', 'Hungarian Forint', 'HUF'),
  ('INR', 'Indian Rupee', 'INR'),
  ('JPY', 'Japanese Yen', 'JPY'),
  ('KGS', 'Kyrgyzstani Som', 'KGS'),
  ('KZT', 'Kazakhstani Tenge', 'KZT'),
  ('MDL', 'Moldovan Leu', 'MDL'),
  ('MXN', 'Mexican Peso', 'MXN'),
  ('NOK', 'Norwegian Krone', 'NOK'),
  ('NZD', 'New Zealand Dollar', 'NZD'),
  ('PLN', 'Polish Zloty', 'PLN'),
  ('RON', 'Romanian Leu', 'RON'),
  ('SEK', 'Swedish Krona', 'SEK'),
  ('SGD', 'Singapore Dollar', 'SGD'),
  ('THB', 'Thai Baht', 'THB'),
  ('TRY', 'Turkish Lira', 'TRY'),
  ('UAH', 'Ukrainian Hryvnia', 'UAH'),
  ('USD', 'US Dollar', '$'),
  ('UZS', 'Uzbekistani Som', 'UZS'),
  ('ZAR', 'South African Rand', 'ZAR')
on conflict (code) do update
set
  name = excluded.name,
  symbol = excluded.symbol,
  is_active = true;
